// <auto-generated />
using System;
using BookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529073308_ResourceSeedingFinalFix")]
    partial class ResourceSeedingFinalFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Microsoft.EntityFrameworkCore.Diagnostics.PendingModelChangesWarning", "Ignore")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("typeRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 208, DateTimeKind.Utc).AddTicks(2711),
                            Description = "",
                            RoomName = "Meeting Room 01",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4121),
                            Description = "",
                            RoomName = "Meeting Room 02",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4174),
                            Description = "",
                            RoomName = "Meeting Room 03",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4212),
                            Description = "",
                            RoomName = "Meeting Room 04",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4216),
                            Description = "",
                            RoomName = "Meeting Room 05",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4232),
                            Description = "",
                            RoomName = "Meeting Room 06",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4241),
                            Description = "",
                            RoomName = "Meeting Room 07",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4258),
                            Description = "",
                            RoomName = "Meeting Room 08",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4269),
                            Description = "",
                            RoomName = "Meeting Room 09",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4274),
                            Description = "",
                            RoomName = "Meeting Room 10",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4476),
                            Description = "",
                            RoomName = "DB-Server Cluster 01",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4485),
                            Description = "",
                            RoomName = "DB-Server Cluster 02",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4487),
                            Description = "",
                            RoomName = "DB-Server Cluster 03",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4491),
                            Description = "",
                            RoomName = "DB-Server Cluster 04",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4493),
                            Description = "",
                            RoomName = "DB-Server Cluster 05",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4496),
                            Description = "",
                            RoomName = "DB-Server Cluster 06",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4504),
                            Description = "",
                            RoomName = "DB-Server Cluster 07",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4509),
                            Description = "",
                            RoomName = "DB-Server Cluster 08",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4519),
                            Description = "",
                            RoomName = "DB-Server Cluster 09",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 0,
                            CreatedDate = new DateTime(2026, 5, 29, 7, 33, 8, 209, DateTimeKind.Utc).AddTicks(4522),
                            Description = "",
                            RoomName = "DB-Server Cluster 10",
                            typeRoom = 1
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.ResourceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Features")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("RoomImages")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId")
                        .IsUnique();

                    b.ToTable("ResourceDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Smart TV 55\", Whiteboard",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 1 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1300.00m,
                            PricePerHour = 170.00m,
                            ResourceId = 1,
                            RoomImages = "[\"assets/images/rooms/room-1.jpg\"]"
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Smart TV 55\", Whiteboard",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 1 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1400.00m,
                            PricePerHour = 190.00m,
                            ResourceId = 2,
                            RoomImages = "[\"assets/images/rooms/room-2.jpg\"]"
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Smart TV 55\", Whiteboard",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 1 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1500.00m,
                            PricePerHour = 210.00m,
                            ResourceId = 3,
                            RoomImages = "[\"assets/images/rooms/room-3.jpg\"]"
                        },
                        new
                        {
                            Id = 4,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Smart TV 55\", Whiteboard",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 1 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1600.00m,
                            PricePerHour = 230.00m,
                            ResourceId = 4,
                            RoomImages = "[\"assets/images/rooms/room-4.jpg\"]"
                        },
                        new
                        {
                            Id = 5,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Smart TV 55\", Whiteboard",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 2 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1700.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 5,
                            RoomImages = "[\"assets/images/rooms/room-5.jpg\"]"
                        },
                        new
                        {
                            Id = 6,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Projector 4K, Sound System",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 2 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1800.00m,
                            PricePerHour = 270.00m,
                            ResourceId = 6,
                            RoomImages = "[\"assets/images/rooms/room-6.jpg\"]"
                        },
                        new
                        {
                            Id = 7,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Projector 4K, Sound System",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 2 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 1900.00m,
                            PricePerHour = 290.00m,
                            ResourceId = 7,
                            RoomImages = "[\"assets/images/rooms/room-7.jpg\"]"
                        },
                        new
                        {
                            Id = 8,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Projector 4K, Sound System",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 2 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 2000.00m,
                            PricePerHour = 310.00m,
                            ResourceId = 8,
                            RoomImages = "[\"assets/images/rooms/room-8.jpg\"]"
                        },
                        new
                        {
                            Id = 9,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Projector 4K, Sound System",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 3 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 2100.00m,
                            PricePerHour = 330.00m,
                            ResourceId = 9,
                            RoomImages = "[\"assets/images/rooms/room-9.jpg\"]"
                        },
                        new
                        {
                            Id = 10,
                            Amenities = "Free Coffee & Water, Air Conditioner",
                            ContactPerson = "Admin Team A",
                            Features = "Projector 4K, Sound System",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ชั้นที่ 3 โซน A อาคาร HQ",
                            PhoneNumber = "02-123-4567",
                            PricePerDay = 2200.00m,
                            PricePerHour = 350.00m,
                            ResourceId = 10,
                            RoomImages = "[\"assets/images/rooms/room-10.jpg\"]"
                        },
                        new
                        {
                            Id = 11,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 16 Cores, RAM: 64GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 01 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 650.00m,
                            PricePerHour = 80.00m,
                            ResourceId = 11,
                            RoomImages = "[\"assets/images/servers/server-1.jpg\"]"
                        },
                        new
                        {
                            Id = 12,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 16 Cores, RAM: 64GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 02 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 650.00m,
                            PricePerHour = 80.00m,
                            ResourceId = 12,
                            RoomImages = "[\"assets/images/servers/server-2.jpg\"]"
                        },
                        new
                        {
                            Id = 13,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 16 Cores, RAM: 64GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 03 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 650.00m,
                            PricePerHour = 80.00m,
                            ResourceId = 13,
                            RoomImages = "[\"assets/images/servers/server-3.jpg\"]"
                        },
                        new
                        {
                            Id = 14,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 16 Cores, RAM: 64GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 04 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 650.00m,
                            PricePerHour = 80.00m,
                            ResourceId = 14,
                            RoomImages = "[\"assets/images/servers/server-4.jpg\"]"
                        },
                        new
                        {
                            Id = 15,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 16 Cores, RAM: 64GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 05 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 650.00m,
                            PricePerHour = 80.00m,
                            ResourceId = 15,
                            RoomImages = "[\"assets/images/servers/server-5.jpg\"]"
                        },
                        new
                        {
                            Id = 16,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 64 Cores, RAM: 256GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 06 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 1800.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 16,
                            RoomImages = "[\"assets/images/servers/server-6.jpg\"]"
                        },
                        new
                        {
                            Id = 17,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 64 Cores, RAM: 256GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 07 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 1800.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 17,
                            RoomImages = "[\"assets/images/servers/server-7.jpg\"]"
                        },
                        new
                        {
                            Id = 18,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 64 Cores, RAM: 256GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 08 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 1800.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 18,
                            RoomImages = "[\"assets/images/servers/server-8.jpg\"]"
                        },
                        new
                        {
                            Id = 19,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 64 Cores, RAM: 256GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 09 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 1800.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 19,
                            RoomImages = "[\"assets/images/servers/server-9.jpg\"]"
                        },
                        new
                        {
                            Id = 20,
                            Amenities = "Uptime 99.99%, Automated Backup",
                            ContactPerson = "DevOps Team",
                            Features = "vCPU: 64 Cores, RAM: 256GB",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "ตู้ Rack เลขที่ 10 ห้อง DataCenter ชั้น 5",
                            PhoneNumber = "02-999-8888",
                            PricePerDay = 1800.00m,
                            PricePerHour = 250.00m,
                            ResourceId = 20,
                            RoomImages = "[\"assets/images/servers/server-10.jpg\"]"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.ResourceDetail", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Resource", "Resource")
                        .WithOne("ResourceDetail")
                        .HasForeignKey("BookingSystem.Domain.Entities.ResourceDetail", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ResourceDetail");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
