// <auto-generated />
using System;
using BookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeSlot")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 01 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 01",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 02 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 02",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 03 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 03",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 04 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 04",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 05 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 05",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 06 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 06",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 07 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 07",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 08 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 08",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 09 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 09",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 0,
                            Description = "ห้องประชุมหมายเลข 10 พร้อมระบบโปรเจกเตอร์",
                            RoomName = "Room 10",
                            typeRoom = 0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 01 (High Performance)",
                            RoomName = "DB-Server 01",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 02 (High Performance)",
                            RoomName = "DB-Server 02",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 03 (High Performance)",
                            RoomName = "DB-Server 03",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 04 (High Performance)",
                            RoomName = "DB-Server 04",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 05 (High Performance)",
                            RoomName = "DB-Server 05",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 06 (High Performance)",
                            RoomName = "DB-Server 06",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 07 (High Performance)",
                            RoomName = "DB-Server 07",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 08 (High Performance)",
                            RoomName = "DB-Server 08",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 09 (High Performance)",
                            RoomName = "DB-Server 09",
                            typeRoom = 1
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 0,
                            Description = "เซิร์ฟเวอร์ฐานข้อมูลเครื่องที่ 10 (High Performance)",
                            RoomName = "DB-Server 10",
                            typeRoom = 1
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
